export class GetEmployees{
    empId!:string;
    firstName!:string;
    lastName!:string;
    gender!:string;
    email!:string;
    dateOfBirth!:string;
    qualification!:string;
    empRole!:string;
    mobileNumber!:number;
    password!:string;
    designation!:string;
    reportingManagerName!:string;
    image!:string;
    currency!:string;
    salary!:string;
    bankName!:string;
    accountHolderName!:string;
    accountType!:string;
    accountNumber!:string;
    ifscCode!:string;
    isActive!:number;
}
